#开发环境配置

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    url: jdbc:mysql://localhost:35076/duck-server?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: 12345678

logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    com:
      duck:
        common:
          server: debug


